### ISSUE TITLE
Number of parameters

### ISSUE THREAD

**Issue by echoofluoc** [JinyuanLiu-CV/MFEIF#2]
It seems the parameters of this network is 370,114, not the result **158K** listed in your paper.

**Comment by haku-huang** [comment]
We apologize for the inconvenience. 
In order to improve the efficiency of the fuse operation, we re-implemented the network described in the paper using PyTorch, which replaces the previous version with TensorFlow used to test the number of parameters. 
We guess that the change in the number of parameters is related to a change in the framework.
The current computing speed (PyTorch) should be much higher than the previous version (TensorFlow).
